[package]
name = "vm_writer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
strum.workspace = true
strum_macros.workspace = true
symbol_table.workspace = true